---
apiVersion: v1
kind: Namespace
metadata:
  name: hacker-company

---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: frontend
spec:
  containers:
  - name: nginx
    image: nginx:stable
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frontend
  namespace: hacker-company

rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    name: frontend
  ports:
  - port: 8888
    targetPort: 80
